"""Run a tiny end-to-end CSFSeg command-line smoke test.

This script creates synthetic 4D fMRI NIfTI files and a randomly initialized
3-channel checkpoint, then runs the real CLI commands. It checks that the
toolkit workflow can execute and write expected outputs. It does not test
scientific segmentation quality.
"""

from __future__ import annotations

import argparse
import csv
import os
import shutil
import subprocess
import sys
from pathlib import Path

import nibabel as nib
import numpy as np
import torch

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from csfseg.models.unet3d import UNet3D_NoZDown


MARKER_NAME = ".csfseg_smoke_dir"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Create synthetic inputs and run the CSFSeg CLI end to end.")
    parser.add_argument(
        "--work-dir",
        default=Path(__file__).resolve().parent / "smoke_run",
        type=Path,
        help="Directory for generated inputs and outputs. Default: examples/smoke_run.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Delete an existing smoke-test directory before running.",
    )
    parser.add_argument(
        "--device",
        default="cpu",
        help="Device passed to csfseg predict/batch. Default: cpu.",
    )
    args = parser.parse_args(argv)

    work_dir = args.work_dir.expanduser().resolve()
    prepare_work_dir(work_dir, overwrite=args.overwrite)

    inputs_dir = work_dir / "inputs"
    checkpoint_dir = work_dir / "checkpoints"
    single_out = work_dir / "single_outputs"
    batch_out = work_dir / "batch_outputs"
    inputs_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    input_one = inputs_dir / "sub-smoke001_task-rest_bold.nii.gz"
    input_two = inputs_dir / "sub-smoke002_task-rest_bold.nii.gz"
    checkpoint_path = checkpoint_dir / "smoke_random_3ch.pt"
    input_paths_csv = work_dir / "input_paths.csv"

    write_synthetic_fmri(input_one, seed=1, x_shift=0.0)
    write_synthetic_fmri(input_two, seed=2, x_shift=1.5)
    write_smoke_checkpoint(checkpoint_path)
    write_manifest(input_paths_csv, [(input_one, "sub-smoke001"), (input_two, "sub-smoke002")])

    run_cli(
        "check-manifest",
        "--input-paths",
        input_paths_csv,
        "--out-dir",
        batch_out,
    )
    run_cli(
        "check-preprocessing",
        "--input",
        input_one,
        "--out-dir",
        single_out,
        "--output-id",
        "sub-smoke001_single",
    )
    run_cli(
        "predict",
        "--input",
        input_one,
        "--out-dir",
        single_out,
        "--checkpoint",
        checkpoint_path,
        "--output-id",
        "sub-smoke001_single",
        "--device",
        args.device,
        "--threshold",
        "0.0",
    )
    run_cli(
        "batch",
        "--input-paths",
        input_paths_csv,
        "--out-dir",
        batch_out,
        "--checkpoint",
        checkpoint_path,
        "--device",
        args.device,
        "--threshold",
        "0.0",
        "--skip-existing",
    )
    run_cli(
        "select-voxels",
        "--out-dir",
        batch_out,
        "--selection-file",
        "reports/selection_template.csv",
        "--selection-name",
        "smoke_manual",
    )

    print("\nSmoke test complete.")
    print(f"Work directory: {work_dir}")
    print("Key files:")
    for path in [
        single_out / "qc" / "sub-smoke001_single_preprocessing_qc.png",
        single_out / "qc" / "sub-smoke001_single_prediction_qc.png",
        batch_out / "reports" / "batch_report.csv",
        batch_out / "reports" / "failed_inputs.csv",
        batch_out / "reports" / "selection_template.csv",
        batch_out / "reports" / "smoke_manual_selection_summary.csv",
    ]:
        print(f"  {path}")
    return 0


def prepare_work_dir(work_dir: Path, *, overwrite: bool) -> None:
    if work_dir.exists():
        marker = work_dir / MARKER_NAME
        if not overwrite:
            raise SystemExit(f"Smoke work directory already exists: {work_dir}\nPass --overwrite to recreate it.")
        if not marker.exists():
            raise SystemExit(
                f"Refusing to delete {work_dir} because it does not look like a CSFSeg smoke-test directory."
            )
        shutil.rmtree(work_dir)
    work_dir.mkdir(parents=True, exist_ok=True)
    (work_dir / MARKER_NAME).write_text("Generated by examples/run_smoke_test.py\n")


def write_synthetic_fmri(path: Path, *, seed: int, x_shift: float) -> None:
    rng = np.random.default_rng(seed)
    x_size, y_size, z_size, t_size = 18, 20, 12, 16
    x, y, z = np.indices((x_size, y_size, z_size), dtype=np.float32)
    cx = (x_size - 1) / 2 + x_shift
    cy = (y_size - 1) / 2
    cz = 4.0
    brain = ((x - cx) / 6.5) ** 2 + ((y - cy) / 7.5) ** 2 + ((z - cz) / 5.5) ** 2 < 1.0
    bottom_band = brain & (z <= 3)

    time = np.arange(t_size, dtype=np.float32)
    slow_wave = np.sin(2 * np.pi * time / t_size)
    fast_wave = np.cos(4 * np.pi * time / t_size)

    data = np.zeros((x_size, y_size, z_size, t_size), dtype=np.float32)
    base = 900.0 + 8.0 * z[..., None]
    signal = base + 18.0 * slow_wave + 4.0 * fast_wave
    noise = rng.normal(0.0, 3.0, size=data.shape).astype(np.float32)
    data[brain] = signal[brain] + noise[brain]
    data[bottom_band] += 20.0 * slow_wave

    affine = np.diag([2.0, 2.0, 2.0, 1.0])
    image = nib.Nifti1Image(data, affine)
    image.header.set_zooms((2.0, 2.0, 2.0, 0.8))
    path.parent.mkdir(parents=True, exist_ok=True)
    nib.save(image, path)


def write_smoke_checkpoint(path: Path) -> None:
    torch.manual_seed(0)
    model = UNet3D_NoZDown(in_channels=3, base=16, out_channels=1)
    checkpoint = {
        "model": model.state_dict(),
        "metadata": {
            "model": "UNet3D_NoZDown",
            "in_channels": 3,
            "channels": ["mean", "std", "tsnr"],
            "base": 16,
            "depth": 10,
            "out_hw": [128, 128],
            "normalization": "nonzero_zscore",
            "requires_finetuning": False,
            "smoke_test_only": True,
        },
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(checkpoint, path)


def write_manifest(rows_path: Path, rows: list[tuple[Path, str]]) -> None:
    with rows_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["input_path", "output_id"])
        writer.writeheader()
        for input_path, output_id in rows:
            writer.writerow({"input_path": str(input_path), "output_id": output_id})


def run_cli(*args: object) -> None:
    cmd = [sys.executable, "-m", "csfseg.cli", *[str(arg) for arg in args]]
    print("\n$ " + " ".join(cmd), flush=True)
    env = os.environ.copy()
    env.setdefault("MPLBACKEND", "Agg")
    subprocess.run(cmd, check=True, env=env)


if __name__ == "__main__":
    raise SystemExit(main())
